### ISSUE TITLE
提交一处bug

### ISSUE THREAD

**Issue by nvv5** [xiaxichen/DY-DanMu#1]
感谢作者的项目加速了我学习golang的进程，在测试中发现了一处bug，还望及时修复。
心跳包的发送周期是45秒是对的，但是那里时间单位错了。  
https://github.com/xiaxichen/DY-DanMu/blob/c5f137116f953febf55ec5a91b8db09979b375c4/spider/client/client.go#L140
应该是毫秒级`time.Sleep(time.Millisecond * 500)`

**Comment by xiaxichen** [comment]
好的谢谢！
